language: python
python:
  -  3.7

branches:
  only:
    - gh_pages

before_install:
    - export TZ='Asia/Shanghai'

install:
  - pip install -r requirements.txt

script:
  - mkdocs build --clean

deploy:
  provider: pages
  github_token: $GITHUB_API_KEY
  skip_cleanup: true
  keep_history: true
  target_branch: master
  local_dir: site
  on:
    branch: gh_pages